version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5006:5006"
    environment:
      - ASPNETCORE_URLS=http://+:5006
      - ConnectionStrings__DefaultConnection:Server=host.docker.internal\\SQLEXPRESS;Database=TaskLearningDb;Trusted_Connection=True;

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"


# docker compose up --build
